# Paths that only made sense on the SmartBear site
[[redirects]]
  from = "/tools"
  to = "/"
  status = 301
[[redirects]]
  from = "/tools/cucumber-open"
  to = "/"
  status = 301

# Paths for SmartBear products
[[redirects]]
  from = "/tools/cucumberstudio"
  to = "https://smartbear.com/product/cucumberstudio/"
  status = 301
[[redirects]]
  from = "/tools/cucumberstudio/*"
  to = "https://smartbear.com/product/cucumberstudio/:splat/"
  status = 301
[[redirects]]
  from = "/tools/cucumber-for-jira"
  to = "https://smartbear.com/product/cucumber-for-jira/"
  status = 301
[[redirects]]
  from = "/tools/cucumber-for-jira/*"
  to = "https://smartbear.com/product/cucumber-for-jira/:splat/"
  status = 301

# Simplified paths
[[redirects]]
  from = "/tools/cucumber-open/sponsors"
  to = "/sponsors"
  status = 301

# Vanity URLs for external stuff
[[redirects]]
  from = "/conduct"
  to = "https://github.com/cucumber/.github/tree/main?tab=coc-ov-file"
  status = 302

# Blog posts with parens in the slug
[[redirects]]
  from = "/blog/bdd/understanding-screenplay-(part-4)"
  to = "/blog/bdd/understanding-screenplay-part-4"
  status = 301
[[redirects]]
  from = "/blog/bdd/understanding-screenplay-(part-3)"
  to = "/blog/bdd/understanding-screenplay-part-3"
  status = 301
[[redirects]]
  from = "/blog/bdd/understanding-screenplay-(part-2)"
  to = "/blog/bdd/understanding-screenplay-part-2"
  status = 301
[[redirects]]
  from = "/blog/bdd/understanding-screenplay-(part-1)"
  to = "/blog/bdd/understanding-screenplay-part-1"
  status = 301
[[redirects]]
  from = "/blog/bdd/user-stories-and-bdd-(part-2)-discovery"
  to = "/blog/bdd/user-stories-and-bdd-part-2-discovery"
  status = 301
[[redirects]]
  from = "/blog/bdd/what-is-good-code-(1)"
  to = "/blog/bdd/what-is-good-code"
  status = 301
[[redirects]]
  from = "/blog/bdd/keep-your-scenarios-brief-(1)"
  to = "/blog/bdd/keep-your-scenarios-brief"
  status = 301

# Relocated docs
[[redirects]]
  from = "/docs/community/get-in-touch"
  to = "/docs/community"
  status = 301
[[redirects]]
  from = "/docs/community/contributing"
  to = "/docs/contributing"
  status = 301
[[redirects]]
  from = "/docs/community/contributing-to-documentation"
  to = "https://github.com/cucumber/website/blob/main/CONTRIBUTING.md"
  status = 301